package ExceptionHandling;

import java.util.InputMismatchException;
import java.util.Scanner;

public class TryCatch {
	public static void main(String args[]) {
		Scanner sc = new Scanner(System.in);
		
		try {
			System.out.println("enter no1");
			int a = sc.nextInt();
			System.out.println("enter no 2");
			int b = sc.nextInt();
			int c = a / b; //--create object of ArithmeticException
			System.out.println("division" + c);
		} catch (ArithmeticException e) {
			System.out.println(e);
			System.out.println("cannot divide by zero..");
		}
		catch (InputMismatchException e) {
			System.out.println(e);
			System.out.println("cannot divide by zero..");
		}
		System.out.println("run cpde....");

	}
}
